
# Example:
  # hmap = get_template_fields("resume_js_str", "./template_0")
  # hmap["website-title"] = "changed"
  # get_override_info_from_hashmap(hmap)

require 'execjs'
require 'json'

module Functions::WebResume::OverrideHelper
  # Call this function to get template elements
  def self.get_template_fields(resume_js_str, template_root_path)
    src = resume_js_str
    src = src + File.read(template_root_path + "/js/resume_adapter_common.js")
    src = src + File.read(template_root_path + "/js/resume_adapter.js")
    context = ExecJS.compile(src)
    result = context.call("get_fields_from_resume_js")
    puts result.class
    return result
  end

  def self.get_override_info_from_hashmap(hmap)
    json_info = hmap.to_json
    str = "/**
    * This file is generated by the Override Helper to support editing features.
    */

    function user_override() {
        return #{json_info};
    }"
    return str
  end

end
