name: "Front end CI/CD"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: GIT CLONE
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 3.234.246.243
        username: centos
        key: ${{ secrets.SSH_USER }}
        script: cd frontend_with_user && git pull
    - name: BUILD
      uses: appleboy/ssh-action@v0.1.6
      with:
        username: centos
        host: 3.234.246.243
        key: ${{ secrets.SSH_USER }}
        script: cd frontend_with_user && podman build -t 6156 -f Dockerfile.development
    - name: RUN
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 3.234.246.243
        username: centos
        key: ${{ secrets.SSH_USER }}
        script: podman run -d -e PORT=8000 -p 8000:8000 localhost/6156:latest
